name: AssetStudioBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.9,)'
      
      - name: Download FBX SDK
        run: |
          md fbx
          cd fbx
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_win.exe" -OutFile "fbxsdk.exe"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_pdbs.exe" -OutFile "fbxpdb.exe"
          Start-Process -FilePath "fbxpdb.exe" /S -Wait
          cd ..

      - name: Nuget Restore
        run: nuget restore
      
      - name: Build .Net472
        run: msbuild /p:Configuration=Release /p:Platform=x64 /p:TargetFramework=net472 /verbosity:minimal

      - name: Build .Net6
        run: msbuild /t:AssetStudioGUI:publish /p:Platform=x64 /p:Configuration=Release /p:TargetFramework=net6.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Build .Net8
        run: msbuild /t:AssetStudioGUI:publish /p:Platform=x64 /p:Configuration=Release /p:TargetFramework=net8.0-windows /p:SelfContained=false /verbosity:minimal

      - name: Upload .Net472 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AssetStudio.net472
          path: AssetStudioGUI/bin/Release/net472

      - name: Upload .Net6 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AssetStudio.net6
          path: AssetStudioGUI/bin/Release/net6.0-windows/publish

      - name: Upload .Net5 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AssetStudio.net8
          path: AssetStudioGUI/bin/Release/net8.0-windows/publish
